package core

import (
	"fmt"
	"math"
	"slices"

	"matplotlib-go/internal/geom"
	"matplotlib-go/render"
)

// EventOrientation controls whether eventplot lines are drawn vertically or horizontally.
type EventOrientation uint8

const (
	EventOrientationVertical EventOrientation = iota
	EventOrientationHorizontal
)

// EventPlotOptions configures Axes.Eventplot.
type EventPlotOptions struct {
	Orientation EventOrientation
	LineOffsets []float64
	LineLengths []float64
	Colors      []render.Color
	LineWidth   float64
	Alpha       float64
	Label       string
}

// EventCollection is a thin LineCollection wrapper used for eventplot.
type EventCollection struct {
	LineCollection
	Positions   [][]float64
	Orientation EventOrientation
	LineOffsets []float64
	LineLengths []float64
}

// HexbinOptions configures Axes.Hexbin.
type HexbinOptions struct {
	GridSizeX int
	GridSizeY int
	Extent    *geom.Rect
	C         []float64
	Reduce    string
	MinCount  int
	Colormap  string
	VMin      *float64
	VMax      *float64
	Alpha     float64
	EdgeColor *render.Color
	LineWidth float64
	Label     string
}

// HexbinCollection is a scalar-mappable polygon collection generated by hexbin.
type HexbinCollection struct {
	PolyCollection
	BinCenters []geom.Pt
	Values     []float64
	Counts     []float64
}

type hexbinKey struct {
	lattice  int
	row, col int
}

// PieOptions configures Axes.Pie.
type PieOptions struct {
	Center           geom.Pt
	Radius           float64
	Width            float64
	StartAngle       float64
	CounterClockwise *bool
	Colors           []render.Color
	Labels           []string
	Explode          []float64
	AutoPct          string
	LabelDistance    float64
	PctDistance      float64
	EdgeColor        *render.Color
	LineWidth        float64
	Alpha            float64
	Coords           CoordinateSpec
	Frame            *bool
}

// PieContainer groups the wedge and text artists created by Axes.Pie.
type PieContainer struct {
	Wedges   []*Wedge
	Labels   []*Text
	AutoText []*Text
}

// ViolinOptions configures Axes.Violinplot.
type ViolinOptions struct {
	Positions   []float64
	Widths      []float64
	Colors      []render.Color
	EdgeColor   *render.Color
	EdgeWidth   float64
	Alpha       float64
	Bandwidth   float64
	Points      int
	LineColor   *render.Color
	ShowMeans   *bool
	ShowMedians *bool
	ShowExtrema *bool
	Label       string
}

// ViolinContainer groups the collections created by Axes.Violinplot.
type ViolinContainer struct {
	Bodies  *PolyCollection
	Means   *LineCollection
	Medians *LineCollection
	Extrema *LineCollection
}

// TableOptions configures Axes.Table.
type TableOptions struct {
	CellText        [][]string
	CellColors      [][]render.Color
	RowLabels       []string
	ColLabels       []string
	BBox            geom.Rect
	Coords          CoordinateSpec
	FontSize        float64
	TextColor       render.Color
	HeaderTextColor render.Color
	HeaderFillColor render.Color
	CellFillColor   render.Color
	EdgeColor       render.Color
	LineWidth       float64
}

type tableCell struct {
	Text     string
	Fill     render.Color
	IsHeader bool
	Rect     geom.Rect
}

// Table renders a simple grid of cells with optional row and column headers.
type Table struct {
	Cells           [][]tableCell
	BBox            geom.Rect
	Coords          CoordinateSpec
	FontSize        float64
	TextColor       render.Color
	HeaderTextColor render.Color
	EdgeColor       render.Color
	LineWidth       float64
	z               float64
}

// SankeyOptions configures a lightweight builder for Sankey-like ribbon diagrams.
type SankeyOptions struct {
	Center     geom.Pt
	Coords     CoordinateSpec
	Scale      float64
	TrunkWidth float64
	PathLength float64
	Gap        float64
	Offset     float64
	Alpha      float64
	TextColor  render.Color
	FontSize   float64
	EdgeColor  *render.Color
	FaceColor  *render.Color
}

// SankeyAddOptions configures one diagram added through the builder.
type SankeyAddOptions struct {
	Labels       []string
	Orientations []int
	Colors       []render.Color
	OffsetX      float64
	OffsetY      float64
	PathLength   float64
}

// Sankey accumulates one or more simple ribbon diagrams on a single axes.
type Sankey struct {
	ax       *Axes
	opts     SankeyOptions
	diagrams []*SankeyDiagram
	cursor   geom.Pt
}

// SankeyDiagram groups the artists emitted for one builder Add call.
type SankeyDiagram struct {
	Trunk   *Rectangle
	Ribbons []*PathPatch
	Labels  []*Text
	Values  []*Text
	Flows   []float64
	Center  geom.Pt
}

// Wedge draws a pie-slice-style circular sector or ring segment.
type Wedge struct {
	Patch
	Center geom.Pt
	Radius float64
	Width  float64
	Theta1 float64
	Theta2 float64
	Coords CoordinateSpec
}

// Add supports the Matplotlib-style builder workflow: create one diagram and
// append its artists to the axes immediately.
func (s *Sankey) Add(flows []float64, opts ...SankeyAddOptions) *SankeyDiagram {
	if s == nil || s.ax == nil || len(flows) == 0 {
		return nil
	}

	cfg := SankeyAddOptions{}
	if len(opts) > 0 {
		cfg = opts[0]
	}

	center := geom.Pt{X: s.cursor.X + cfg.OffsetX, Y: s.cursor.Y + cfg.OffsetY}
	pathLength := s.opts.PathLength
	if cfg.PathLength > 0 {
		pathLength = cfg.PathLength
	}

	scale := s.opts.Scale
	if scale <= 0 {
		scale = 1
	}
	trunkWidth := s.opts.TrunkWidth
	if trunkWidth <= 0 {
		trunkWidth = 0.08
	}
	gap := s.opts.Gap
	if gap <= 0 {
		gap = 0.01
	}
	alpha := clampOneToOne(s.opts.Alpha)
	if alpha == 0 {
		alpha = 1
	}
	edgeColor := render.Color{R: 0, G: 0, B: 0, A: 1}
	if s.opts.EdgeColor != nil {
		edgeColor = *s.opts.EdgeColor
	}
	defaultFace := s.ax.NextColor()
	if s.opts.FaceColor != nil {
		defaultFace = *s.opts.FaceColor
	}

	totalIn := 0.0
	totalOut := 0.0
	for _, flow := range flows {
		if flow >= 0 {
			totalIn += flow
		} else {
			totalOut += math.Abs(flow)
		}
	}
	if totalIn == 0 && totalOut == 0 {
		return nil
	}

	trunkHeight := math.Max(totalIn, totalOut) * scale
	if trunkHeight <= 0 {
		trunkHeight = trunkWidth
	}
	if trunkHeight < trunkWidth {
		trunkHeight = trunkWidth
	}
	trunkLength := math.Max(pathLength, trunkWidth*2)
	trunk := &Rectangle{
		Patch: Patch{
			FaceColor: patchAlphaColor(defaultFace, alpha),
			EdgeColor: edgeColor,
			EdgeWidth: 1,
			z:         2,
		},
		XY:     geom.Pt{X: center.X - trunkLength/2, Y: center.Y - trunkHeight/2},
		Width:  trunkLength,
		Height: trunkHeight,
		Coords: s.opts.Coords,
	}
	diagram := &SankeyDiagram{
		Trunk:  trunk,
		Flows:  append([]float64(nil), flows...),
		Center: center,
	}

	body := sankeyBodyPath(center, trunkLength, pathLength, trunkHeight, math.Max(trunkWidth, gap))
	bodyPatch := &PathPatch{
		Patch: Patch{
			FaceColor: patchAlphaColor(defaultFace, alpha),
			EdgeColor: edgeColor,
			EdgeWidth: 1,
			Alpha:     1,
			z:         2.2,
		},
		Path:   body,
		Coords: s.opts.Coords,
	}
	s.ax.AddPatch(bodyPatch)
	diagram.Ribbons = append(diagram.Ribbons, bodyPatch)

	labelPositions := sankeyLabelPositions(center, trunkLength, pathLength, trunkHeight, flows, cfg.Orientations)
	for i, flow := range flows {
		label := stringAt("", cfg.Labels, i)
		if label == "" || i >= len(labelPositions) {
			continue
		}
		pos := labelPositions[i]
		txt := s.ax.Text(pos.point.X, pos.point.Y, label, TextOptions{
			Coords:   s.opts.Coords,
			FontSize: s.opts.FontSize,
			Color:    s.opts.TextColor,
			HAlign:   pos.align,
			VAlign:   TextVAlignMiddle,
		})
		diagram.Labels = append(diagram.Labels, txt)
		value := s.ax.Text(pos.point.X, pos.point.Y, fmt.Sprintf("%g", math.Abs(flow)), TextOptions{
			Coords:   s.opts.Coords,
			FontSize: s.opts.FontSize,
			Color:    s.opts.TextColor,
			HAlign:   pos.align,
			VAlign:   TextVAlignMiddle,
			OffsetY:  s.opts.FontSize * 0.9,
		})
		diagram.Values = append(diagram.Values, value)
	}

	s.diagrams = append(s.diagrams, diagram)
	s.cursor.X = center.X + trunkLength + pathLength
	return diagram
}

// Finish returns all diagrams added through the builder.
func (s *Sankey) Finish() []*SankeyDiagram {
	if s == nil {
		return nil
	}
	return append([]*SankeyDiagram(nil), s.diagrams...)
}

func sankeyBodyPath(center geom.Pt, trunkLength, pathLength, trunkHeight, gap float64) geom.Path {
	left := center.X - trunkLength*0.78
	inletRight := left + trunkLength*0.27
	cpuLeft := center.X - trunkLength*0.27
	cpuRight := cpuLeft + trunkLength*0.56
	bodyRight := center.X + trunkLength*0.80 + pathLength*0.35
	wasteBase := center.X + trunkLength*1.02 + pathLength*0.35
	wasteTip := center.X + trunkLength*1.08 + pathLength*0.55
	top := center.Y + trunkHeight*0.42
	midBottom := center.Y - trunkHeight*0.20
	bottom := center.Y - trunkHeight*0.45
	arrowTop := center.Y - trunkHeight*0.33
	arrowBottom := center.Y - trunkHeight*0.58
	arrowTipY := center.Y - trunkHeight*0.78
	channelBottom := center.Y - trunkHeight*0.08
	bodyTop := center.Y + trunkHeight*0.06
	gap = math.Min(math.Max(gap, 0.01), trunkHeight*0.18)

	var path geom.Path

	path.MoveTo(geom.Pt{X: left, Y: top})
	path.LineTo(geom.Pt{X: inletRight, Y: top})
	path.LineTo(geom.Pt{X: inletRight, Y: midBottom})
	path.LineTo(geom.Pt{X: left, Y: midBottom})
	path.Close()

	path.MoveTo(geom.Pt{X: cpuLeft, Y: top - gap})
	path.LineTo(geom.Pt{X: cpuRight, Y: top - gap})
	path.LineTo(geom.Pt{X: cpuRight, Y: channelBottom})
	path.LineTo(geom.Pt{X: cpuLeft, Y: channelBottom})
	path.Close()

	path.MoveTo(geom.Pt{X: inletRight, Y: channelBottom})
	path.CubicTo(
		geom.Pt{X: inletRight, Y: bottom},
		geom.Pt{X: center.X - trunkLength*0.20, Y: bottom},
		geom.Pt{X: center.X + trunkLength*0.10, Y: bottom},
	)
	path.LineTo(geom.Pt{X: bodyRight, Y: bottom})
	path.CubicTo(
		geom.Pt{X: wasteBase, Y: bottom},
		geom.Pt{X: wasteBase, Y: arrowTop},
		geom.Pt{X: wasteBase, Y: arrowTop},
	)
	path.LineTo(geom.Pt{X: wasteTip, Y: arrowTop})
	path.LineTo(geom.Pt{X: wasteBase, Y: arrowTipY})
	path.LineTo(geom.Pt{X: bodyRight, Y: arrowBottom})
	path.LineTo(geom.Pt{X: bodyRight, Y: midBottom})
	path.LineTo(geom.Pt{X: center.X + trunkLength*0.56, Y: midBottom})
	path.CubicTo(
		geom.Pt{X: center.X + trunkLength*0.48, Y: midBottom},
		geom.Pt{X: center.X + trunkLength*0.48, Y: bodyTop},
		geom.Pt{X: center.X + trunkLength*0.38, Y: bodyTop},
	)
	path.LineTo(geom.Pt{X: cpuRight, Y: bodyTop})
	path.CubicTo(
		geom.Pt{X: cpuRight, Y: channelBottom},
		geom.Pt{X: center.X + trunkLength*0.14, Y: channelBottom},
		geom.Pt{X: inletRight, Y: channelBottom},
	)
	path.Close()
	return path
}

type sankeyTextPosition struct {
	point geom.Pt
	align TextAlign
}

func sankeyLabelPositions(center geom.Pt, trunkLength, pathLength, trunkHeight float64, flows []float64, orientations []int) []sankeyTextPosition {
	out := make([]sankeyTextPosition, len(flows))
	topIndex := 0
	for i, flow := range flows {
		side := sankeyOrientation(flow, orientations, i)
		if side < 0 {
			out[i] = sankeyTextPosition{
				point: geom.Pt{X: center.X + trunkLength*1.05 + pathLength*0.48, Y: center.Y - trunkHeight*0.42},
				align: TextAlignLeft,
			}
			continue
		}
		x := center.X + trunkLength*0.07
		if topIndex > 0 {
			x = center.X - trunkLength*0.62
		}
		out[i] = sankeyTextPosition{
			point: geom.Pt{X: x, Y: center.Y + trunkHeight*0.54},
			align: TextAlignCenter,
		}
		topIndex++
	}
	return out
}

// NewSankey creates a lightweight builder that emits ribbon-like diagrams on a single axes.
func NewSankey(ax *Axes, opts ...SankeyOptions) *Sankey {
	if ax == nil {
		return nil
	}
	cfg := SankeyOptions{
		Center:     geom.Pt{X: 0.18, Y: 0.5},
		Coords:     Coords(CoordAxes),
		Scale:      1,
		TrunkWidth: 0.06,
		PathLength: 0.32,
		Gap:        0.004,
		Offset:     0.15,
		Alpha:      1,
		TextColor:  ax.resolvedRC().DefaultTextColor(),
		FontSize:   ax.resolvedRC().FontSize,
	}
	if len(opts) > 0 {
		cfg = opts[0]
		if cfg.Coords == (CoordinateSpec{}) {
			cfg.Coords = Coords(CoordAxes)
		}
		if cfg.Scale <= 0 {
			cfg.Scale = 1
		}
		if cfg.TrunkWidth <= 0 {
			cfg.TrunkWidth = 0.06
		}
		if cfg.PathLength <= 0 {
			cfg.PathLength = 0.18
		}
		if cfg.Gap < 0 {
			cfg.Gap = 0
		}
		if cfg.Offset <= 0 {
			cfg.Offset = 0.15
		}
		if cfg.Alpha <= 0 {
			cfg.Alpha = 1
		}
		if cfg.FontSize <= 0 {
			cfg.FontSize = ax.resolvedRC().FontSize
		}
		if cfg.TextColor == (render.Color{}) {
			cfg.TextColor = ax.resolvedRC().DefaultTextColor()
		}
	}
	return &Sankey{
		ax:     ax,
		opts:   cfg,
		cursor: cfg.Center,
	}
}

// Eventplot adds a collection of short event markers to the axes.
func (a *Axes) Eventplot(positions [][]float64, opts ...EventPlotOptions) *EventCollection {
	if a == nil || len(positions) == 0 {
		return nil
	}
	cfg := EventPlotOptions{
		Orientation: EventOrientationVertical,
		LineWidth:   1.5,
		Alpha:       1,
	}
	if len(opts) > 0 {
		cfg = opts[0]
		if cfg.LineWidth <= 0 {
			cfg.LineWidth = 1.5
		}
		if cfg.Alpha <= 0 {
			cfg.Alpha = 1
		}
	}

	offsets := cfg.LineOffsets
	if len(offsets) == 0 {
		offsets = make([]float64, len(positions))
		for i := range offsets {
			offsets[i] = float64(i + 1)
		}
	}
	lengths := cfg.LineLengths
	if len(lengths) == 0 {
		lengths = make([]float64, len(positions))
		for i := range lengths {
			lengths[i] = 0.8
		}
	}

	segments := make([][]geom.Pt, 0)
	colors := make([]render.Color, 0)
	for i, group := range positions {
		offset := floatAt(offsets, i, float64(i+1))
		length := math.Abs(floatAt(lengths, i, 0.8))
		half := length / 2
		col := colorAt(a.NextColor(), cfg.Colors, i)
		col.A *= clampOneToOne(cfg.Alpha)
		for _, value := range group {
			if !isFinite(value) {
				continue
			}
			segment := []geom.Pt{
				{X: value, Y: offset - half},
				{X: value, Y: offset + half},
			}
			if cfg.Orientation == EventOrientationHorizontal {
				segment = []geom.Pt{
					{X: offset - half, Y: value},
					{X: offset + half, Y: value},
				}
			}
			segments = append(segments, segment)
			colors = append(colors, col)
		}
	}
	if len(segments) == 0 {
		return nil
	}

	collection := &EventCollection{
		LineCollection: LineCollection{
			Collection: Collection{Label: cfg.Label, Alpha: 1, z: 2},
			Segments:   segments,
			Colors:     colors,
			LineWidth:  cfg.LineWidth,
			LineCap:    render.CapButt,
			LineJoin:   render.JoinRound,
		},
		Positions:   positions,
		Orientation: cfg.Orientation,
		LineOffsets: append([]float64(nil), offsets...),
		LineLengths: append([]float64(nil), lengths...),
	}
	a.AddCollection(collection)
	return collection
}

// Hexbin bins points into a staggered hexagonal grid and colors occupied bins by aggregate value.
func (a *Axes) Hexbin(x, y []float64, opts ...HexbinOptions) *HexbinCollection {
	if a == nil || len(x) == 0 || len(y) == 0 {
		return nil
	}

	n := min(len(x), len(y))
	cfg := HexbinOptions{
		GridSizeX: 18,
		MinCount:  1,
		Colormap:  "viridis",
		Alpha:     1,
		LineWidth: 0.75,
	}
	if len(opts) > 0 {
		cfg = opts[0]
		if cfg.GridSizeX <= 0 {
			cfg.GridSizeX = 18
		}
		if cfg.MinCount <= 0 {
			cfg.MinCount = 1
		}
		if cfg.Colormap == "" {
			cfg.Colormap = "viridis"
		}
		if cfg.Alpha <= 0 {
			cfg.Alpha = 1
		}
		if cfg.LineWidth <= 0 {
			cfg.LineWidth = 0.75
		}
	}

	extent := cfg.Extent
	if extent == nil {
		rect := finitePointRect(x[:n], y[:n])
		extent = &rect
	}
	if extent.W() == 0 {
		extent.Max.X = extent.Min.X + 1
	}
	if extent.H() == 0 {
		extent.Max.Y = extent.Min.Y + 1
	}

	gridX := max(1, cfg.GridSizeX)
	gridY := cfg.GridSizeY
	if gridY <= 0 {
		gridY = max(1, int(float64(gridX)/math.Sqrt(3)))
	}

	xMin, xMax := extent.Min.X, extent.Max.X
	yMin, yMax := extent.Min.Y, extent.Max.Y
	padding := 1e-9 * (xMax - xMin)
	xMin -= padding
	xMax += padding

	xStep := (xMax - xMin) / float64(gridX)
	yStep := (yMax - yMin) / float64(gridY)
	if xStep <= 0 {
		xStep = 1
	}
	if yStep <= 0 {
		yStep = 1
	}

	type bin struct {
		center geom.Pt
		count  float64
		sum    float64
	}

	bins := map[hexbinKey]*bin{}
	for i := range n {
		xi, yi := x[i], y[i]
		if !isFinite(xi) || !isFinite(yi) {
			continue
		}
		k, center, ok := matplotlibHexbinCenter(xi, yi, xMin, yMin, gridX, gridY, xStep, yStep)
		if !ok {
			continue
		}
		entry := bins[k]
		if entry == nil {
			entry = &bin{
				center: center,
			}
			bins[k] = entry
		}
		entry.count++
		if i < len(cfg.C) && isFinite(cfg.C[i]) {
			entry.sum += cfg.C[i]
		} else {
			entry.sum += 1
		}
	}
	if len(bins) == 0 {
		return nil
	}

	keys := make([]hexbinKey, 0, len(bins))
	for k := range bins {
		keys = append(keys, k)
	}
	slices.SortFunc(keys, func(a, b hexbinKey) int {
		if a.lattice != b.lattice {
			return a.lattice - b.lattice
		}
		if a.row != b.row {
			return a.row - b.row
		}
		return a.col - b.col
	})

	polygons := make([][]geom.Pt, 0, len(keys))
	values := make([]float64, 0, len(keys))
	counts := make([]float64, 0, len(keys))
	centers := make([]geom.Pt, 0, len(keys))
	rx := xStep / 2
	ry := yStep / 3
	for _, k := range keys {
		entry := bins[k]
		if int(entry.count) < cfg.MinCount {
			continue
		}
		value := entry.count
		if len(cfg.C) > 0 {
			switch cfg.Reduce {
			case "sum":
				value = entry.sum
			case "count":
				value = entry.count
			default:
				value = entry.sum / entry.count
			}
		}
		polygons = append(polygons, specialtyHexagon(entry.center, rx, ry))
		values = append(values, value)
		counts = append(counts, entry.count)
		centers = append(centers, entry.center)
	}
	if len(polygons) == 0 {
		return nil
	}

	mapping := resolveScalarMapValues(values, cfg.Colormap, cfg.VMin, cfg.VMax)
	faceColors := make([]render.Color, len(values))
	for i, value := range values {
		faceColors[i] = mapping.Color(value, cfg.Alpha)
	}
	edgeColor := render.Color{R: 1, G: 1, B: 1, A: 0.9}
	if cfg.EdgeColor != nil {
		edgeColor = *cfg.EdgeColor
	}
	edgeColors := faceColors
	if cfg.EdgeColor != nil {
		edgeColors = nil
	}
	collection := &HexbinCollection{
		PolyCollection: PolyCollection{
			PatchCollection: PatchCollection{
				Collection: Collection{
					Label:    cfg.Label,
					Alpha:    1,
					Colormap: mapping.Colormap,
					VMin:     mapping.VMin,
					VMax:     mapping.VMax,
					z:        2,
				},
				FaceColors: faceColors,
				EdgeColor:  edgeColor,
				EdgeColors: edgeColors,
				EdgeWidth:  cfg.LineWidth,
			},
			Polygons: polygons,
		},
		BinCenters: centers,
		Values:     values,
		Counts:     counts,
	}
	a.AddCollection(collection)
	return collection
}

// Pie draws pie-slice wedges and returns the artists grouped in a container.
func (a *Axes) Pie(values []float64, opts ...PieOptions) *PieContainer {
	if a == nil || len(values) == 0 {
		return nil
	}
	cfg := PieOptions{
		Center:        geom.Pt{},
		Radius:        1,
		StartAngle:    0,
		LabelDistance: 1.15,
		PctDistance:   0.62,
		LineWidth:     1,
		Alpha:         1,
		Coords:        Coords(CoordData),
	}
	if len(opts) > 0 {
		cfg = opts[0]
		if cfg.Radius <= 0 {
			cfg.Radius = 1
		}
		if cfg.LabelDistance <= 0 {
			cfg.LabelDistance = 1.15
		}
		if cfg.PctDistance <= 0 {
			cfg.PctDistance = 0.62
		}
		if cfg.LineWidth <= 0 {
			cfg.LineWidth = 1
		}
		if cfg.Alpha <= 0 {
			cfg.Alpha = 1
		}
		if cfg.Coords == (CoordinateSpec{}) {
			cfg.Coords = Coords(CoordData)
		}
	}

	total := 0.0
	filtered := make([]float64, len(values))
	for i, value := range values {
		if value > 0 && isFinite(value) {
			filtered[i] = value
			total += value
		}
	}
	if total == 0 {
		return nil
	}

	container := &PieContainer{}
	edgeColor := render.Color{R: 1, G: 1, B: 1, A: 1}
	if cfg.EdgeColor != nil {
		edgeColor = *cfg.EdgeColor
	}

	theta := cfg.StartAngle
	counterClockwise := specialtyBool(cfg.CounterClockwise, true)
	for i, value := range filtered {
		if value <= 0 {
			continue
		}
		fraction := value / total
		span := fraction * 360
		end := theta + span
		if !counterClockwise {
			end = theta - span
		}
		mid := (theta + end) / 2
		explode := floatAt(cfg.Explode, i, 0)
		offset := geom.Pt{
			X: math.Cos(mid*math.Pi/180) * cfg.Radius * explode,
			Y: math.Sin(mid*math.Pi/180) * cfg.Radius * explode,
		}
		color := colorAt(a.NextColor(), cfg.Colors, i)
		color.A *= clampOneToOne(cfg.Alpha)
		wedge := &Wedge{
			Patch: Patch{
				FaceColor: color,
				EdgeColor: edgeColor,
				EdgeWidth: cfg.LineWidth,
				Alpha:     1,
				Label:     stringAt("", cfg.Labels, i),
				z:         2,
			},
			Center: geom.Pt{X: cfg.Center.X + offset.X, Y: cfg.Center.Y + offset.Y},
			Radius: cfg.Radius,
			Width:  cfg.Width,
			Theta1: theta,
			Theta2: end,
			Coords: cfg.Coords,
		}
		a.AddPatch(wedge)
		container.Wedges = append(container.Wedges, wedge)

		if label := stringAt("", cfg.Labels, i); label != "" {
			labelPt := piePoint(wedge.Center, cfg.Radius*cfg.LabelDistance, mid)
			clipOn := false
			container.Labels = append(container.Labels, a.Text(labelPt.X, labelPt.Y, label, TextOptions{
				Coords: cfg.Coords,
				HAlign: pieAlign(mid),
				VAlign: TextVAlignMiddle,
				ClipOn: &clipOn,
			}))
		}
		if cfg.AutoPct != "" {
			autoPt := piePoint(wedge.Center, cfg.Radius*cfg.PctDistance, mid)
			autoText := fmt.Sprintf(cfg.AutoPct, fraction*100)
			clipOn := false
			container.AutoText = append(container.AutoText, a.Text(autoPt.X, autoPt.Y, autoText, TextOptions{
				Coords: cfg.Coords,
				HAlign: TextAlignCenter,
				VAlign: TextVAlignMiddle,
				ClipOn: &clipOn,
			}))
		}

		theta = end
	}

	if cfg.Coords == Coords(CoordData) {
		padding := cfg.Radius * 1.25
		a.SetXLim(cfg.Center.X-padding, cfg.Center.X+padding)
		a.SetYLim(cfg.Center.Y-padding, cfg.Center.Y+padding)
		a.SetAxisEqual()
		if !specialtyBool(cfg.Frame, false) {
			hideAxesFrame(a)
		}
	}
	return container
}

// Violinplot draws one violin body per dataset and optional summary lines.
func (a *Axes) Violinplot(data [][]float64, opts ...ViolinOptions) *ViolinContainer {
	if a == nil || len(data) == 0 {
		return nil
	}
	cfg := ViolinOptions{
		EdgeWidth: 1,
		Alpha:     0.65,
		Points:    100,
	}
	if len(opts) > 0 {
		cfg = opts[0]
		if cfg.EdgeWidth <= 0 {
			cfg.EdgeWidth = 1
		}
		if cfg.Alpha <= 0 {
			cfg.Alpha = 0.65
		}
		if cfg.Points < 8 {
			cfg.Points = 100
		}
	}

	polygons := make([][]geom.Pt, 0, len(data))
	faceColors := make([]render.Color, 0, len(data))
	medianSegments := make([][]geom.Pt, 0, len(data))
	meanSegments := make([][]geom.Pt, 0, len(data))
	extremaSegments := make([][]geom.Pt, 0, len(data)*3)

	for i, series := range data {
		values := specialtyFiniteValues(series)
		if len(values) == 0 {
			continue
		}

		width := math.Abs(floatAt(cfg.Widths, i, 0.5))
		if width == 0 {
			width = 0.5
		}
		position := floatAt(cfg.Positions, i, float64(i+1))
		stats := specialtyViolinStats(values)
		grid, density := specialtyKDE(values, cfg.Points, cfg.Bandwidth)
		if len(grid) == 0 || len(density) == 0 {
			continue
		}

		maxDensity := 0.0
		for _, d := range density {
			if d > maxDensity {
				maxDensity = d
			}
		}
		if maxDensity == 0 {
			maxDensity = 1
		}

		left := make([]geom.Pt, 0, len(grid))
		right := make([]geom.Pt, 0, len(grid))
		for j := range grid {
			halfWidth := density[j] / maxDensity * width * 0.5
			left = append(left, geom.Pt{X: position - halfWidth, Y: grid[j]})
			right = append(right, geom.Pt{X: position + halfWidth, Y: grid[j]})
		}
		polygon := make([]geom.Pt, 0, len(left)+len(right))
		polygon = append(polygon, left...)
		for j := len(right) - 1; j >= 0; j-- {
			polygon = append(polygon, right[j])
		}
		polygons = append(polygons, polygon)

		color := colorAt(a.NextColor(), cfg.Colors, i)
		color.A *= clampOneToOne(cfg.Alpha)
		faceColors = append(faceColors, color)

		if specialtyBool(cfg.ShowMeans, false) {
			meanSegments = append(meanSegments, []geom.Pt{
				{X: position - width*0.25, Y: stats.mean},
				{X: position + width*0.25, Y: stats.mean},
			})
		}
		if specialtyBool(cfg.ShowMedians, true) {
			medianSegments = append(medianSegments, []geom.Pt{
				{X: position - width*0.3, Y: stats.median},
				{X: position + width*0.3, Y: stats.median},
			})
		}
		if specialtyBool(cfg.ShowExtrema, true) {
			extremaSegments = append(extremaSegments,
				[]geom.Pt{{X: position, Y: stats.min}, {X: position, Y: stats.max}},
				[]geom.Pt{{X: position - width*0.25, Y: stats.min}, {X: position + width*0.25, Y: stats.min}},
				[]geom.Pt{{X: position - width*0.25, Y: stats.max}, {X: position + width*0.25, Y: stats.max}},
			)
		}
	}

	if len(polygons) == 0 {
		return nil
	}

	edgeColor := render.Color{R: 0.12, G: 0.12, B: 0.12, A: 0.9}
	if cfg.EdgeColor != nil {
		edgeColor = *cfg.EdgeColor
	}
	lineColor := edgeColor
	if cfg.LineColor != nil {
		lineColor = *cfg.LineColor
	}

	container := &ViolinContainer{
		Bodies: &PolyCollection{
			PatchCollection: PatchCollection{
				Collection: Collection{Label: cfg.Label, Alpha: 1, z: 2},
				FaceColors: faceColors,
				EdgeColor:  edgeColor,
				EdgeWidth:  cfg.EdgeWidth,
			},
			Polygons: polygons,
		},
	}
	a.AddCollection(container.Bodies)

	if len(meanSegments) > 0 {
		container.Means = &LineCollection{
			Collection: Collection{Alpha: 1, z: 2.3},
			Segments:   meanSegments,
			Color:      lineColor,
			LineWidth:  math.Max(cfg.EdgeWidth, 1.25),
			LineCap:    render.CapRound,
		}
		a.AddCollection(container.Means)
	}
	if len(medianSegments) > 0 {
		container.Medians = &LineCollection{
			Collection: Collection{Alpha: 1, z: 2.35},
			Segments:   medianSegments,
			Color:      render.Color{R: 1, G: 1, B: 1, A: 0.95},
			LineWidth:  math.Max(cfg.EdgeWidth, 1.5),
			LineCap:    render.CapRound,
		}
		a.AddCollection(container.Medians)
	}
	if len(extremaSegments) > 0 {
		container.Extrema = &LineCollection{
			Collection: Collection{Alpha: 1, z: 2.1},
			Segments:   extremaSegments,
			Color:      lineColor,
			LineWidth:  math.Max(cfg.EdgeWidth*0.9, 1),
			LineCap:    render.CapRound,
		}
		a.AddCollection(container.Extrema)
	}
	return container
}

// Table adds a simple table artist positioned in axes coordinates by default.
func (a *Axes) Table(opts ...TableOptions) *Table {
	if a == nil {
		return nil
	}
	cfg := TableOptions{
		BBox:            geom.Rect{Min: geom.Pt{X: 0, Y: 0}, Max: geom.Pt{X: 1, Y: 1}},
		Coords:          Coords(CoordAxes),
		FontSize:        a.resolvedRC().FontSize,
		TextColor:       a.resolvedRC().DefaultTextColor(),
		HeaderTextColor: a.resolvedRC().DefaultTextColor(),
		HeaderFillColor: render.Color{R: 1, G: 1, B: 1, A: 1},
		CellFillColor:   render.Color{R: 1, G: 1, B: 1, A: 1},
		EdgeColor:       render.Color{R: 0, G: 0, B: 0, A: 1},
		LineWidth:       1,
	}
	if len(opts) > 0 {
		cfg = opts[0]
		if cfg.BBox == (geom.Rect{}) {
			cfg.BBox = geom.Rect{Min: geom.Pt{X: 0, Y: 0}, Max: geom.Pt{X: 1, Y: 1}}
		}
		if cfg.Coords == (CoordinateSpec{}) {
			cfg.Coords = Coords(CoordAxes)
		}
		if cfg.FontSize <= 0 {
			cfg.FontSize = a.resolvedRC().FontSize
		}
		if cfg.TextColor == (render.Color{}) {
			cfg.TextColor = a.resolvedRC().DefaultTextColor()
		}
		if cfg.HeaderTextColor == (render.Color{}) {
			cfg.HeaderTextColor = a.resolvedRC().DefaultTextColor()
		}
		if cfg.HeaderFillColor == (render.Color{}) {
			cfg.HeaderFillColor = render.Color{R: 1, G: 1, B: 1, A: 1}
		}
		if cfg.CellFillColor == (render.Color{}) {
			cfg.CellFillColor = render.Color{R: 1, G: 1, B: 1, A: 1}
		}
		if cfg.EdgeColor == (render.Color{}) {
			cfg.EdgeColor = render.Color{R: 0, G: 0, B: 0, A: 1}
		}
		if cfg.LineWidth <= 0 {
			cfg.LineWidth = 1
		}
	}

	rows := len(cfg.CellText)
	cols := 0
	for _, row := range cfg.CellText {
		cols = max(cols, len(row))
	}
	if rows == 0 && len(cfg.RowLabels) == 0 && len(cfg.ColLabels) == 0 {
		return nil
	}
	if cols == 0 {
		cols = 1
	}

	hasRowLabels := len(cfg.RowLabels) > 0
	hasColLabels := len(cfg.ColLabels) > 0
	gridRows := rows
	if hasColLabels {
		gridRows++
	}
	gridCols := cols + boolOffset(hasRowLabels)
	dataCellW := cfg.BBox.W() / float64(cols)
	rowLabelW := 0.0
	if hasRowLabels {
		rowLabelW = tableRowLabelWidth(cfg.RowLabels, dataCellW)
	}
	cellH := cfg.BBox.H() / float64(gridRows)

	cells := make([][]tableCell, gridRows)
	for r := range gridRows {
		cells[r] = make([]tableCell, gridCols)
		for c := range gridCols {
			cells[r][c] = tableCell{
				Fill: cfg.CellFillColor,
				Rect: tableCellRect(cfg.BBox, gridRows, cols, hasRowLabels, hasColLabels, rowLabelW, r, c),
			}
		}
	}
	if hasColLabels {
		for c := 0; c < cols; c++ {
			col := c + boolOffset(hasRowLabels)
			cells[0][col] = tableCell{
				Text:     stringAt("", cfg.ColLabels, c),
				Fill:     cfg.HeaderFillColor,
				IsHeader: true,
				Rect:     tableCellRect(cfg.BBox, gridRows, cols, hasRowLabels, hasColLabels, rowLabelW, 0, col),
			}
		}
	}
	if hasRowLabels {
		for r := 0; r < rows; r++ {
			row := r + boolOffset(hasColLabels)
			cells[row][0] = tableCell{
				Text:     stringAt("", cfg.RowLabels, r),
				Fill:     cfg.HeaderFillColor,
				IsHeader: true,
				Rect: geom.Rect{
					Min: geom.Pt{X: cfg.BBox.Min.X - rowLabelW, Y: cfg.BBox.Max.Y - float64(row+1)*cellH},
					Max: geom.Pt{X: cfg.BBox.Min.X, Y: cfg.BBox.Max.Y - float64(row)*cellH},
				},
			}
		}
	}
	for r := 0; r < rows; r++ {
		for c := 0; c < cols; c++ {
			fill := cfg.CellFillColor
			if r < len(cfg.CellColors) && c < len(cfg.CellColors[r]) && cfg.CellColors[r][c] != (render.Color{}) {
				fill = cfg.CellColors[r][c]
			}
			row := r + boolOffset(hasColLabels)
			col := c + boolOffset(hasRowLabels)
			cells[row][col] = tableCell{
				Text: stringAt("", cfg.CellText[r], c),
				Fill: fill,
				Rect: tableCellRect(cfg.BBox, gridRows, cols, hasRowLabels, hasColLabels, rowLabelW, row, col),
			}
		}
	}

	table := &Table{
		Cells:           cells,
		BBox:            cfg.BBox,
		Coords:          cfg.Coords,
		FontSize:        cfg.FontSize,
		TextColor:       cfg.TextColor,
		HeaderTextColor: cfg.HeaderTextColor,
		EdgeColor:       cfg.EdgeColor,
		LineWidth:       cfg.LineWidth,
		z:               4,
	}
	a.Add(table)
	return table
}

func tableRowLabelWidth(labels []string, dataCellW float64) float64 {
	maxLen := 0
	for _, label := range labels {
		maxLen = max(maxLen, len([]rune(label)))
	}
	width := 0.015 + float64(maxLen)*0.025
	if width < 0.04 {
		width = 0.04
	}
	if dataCellW > 0 && width > dataCellW*0.5 {
		width = dataCellW * 0.5
	}
	return width
}

func tableCellRect(bbox geom.Rect, gridRows, dataCols int, hasRowLabels, hasColLabels bool, rowLabelW float64, row, col int) geom.Rect {
	if gridRows <= 0 || dataCols <= 0 {
		return geom.Rect{}
	}
	cellH := bbox.H() / float64(gridRows)
	y0 := bbox.Max.Y - float64(row+1)*cellH
	y1 := bbox.Max.Y - float64(row)*cellH
	if hasRowLabels && col == 0 {
		if hasColLabels && row == 0 {
			return geom.Rect{}
		}
		return geom.Rect{
			Min: geom.Pt{X: bbox.Min.X - rowLabelW, Y: y0},
			Max: geom.Pt{X: bbox.Min.X, Y: y1},
		}
	}

	dataCol := col
	if hasRowLabels {
		dataCol--
	}
	if dataCol < 0 || dataCol >= dataCols {
		return geom.Rect{}
	}
	cellW := bbox.W() / float64(dataCols)
	x0 := bbox.Min.X + float64(dataCol)*cellW
	return geom.Rect{
		Min: geom.Pt{X: x0, Y: y0},
		Max: geom.Pt{X: x0 + cellW, Y: y1},
	}
}

// Draw renders the wedge path using the embedded patch styling.
func (w *Wedge) Draw(ren render.Renderer, ctx *DrawContext) {
	if w == nil || ctx == nil || ren == nil || w.Radius <= 0 {
		return
	}
	path := buildDisplayPath(ctx, w.Coords, w.localPath(), geom.Identity())
	w.drawStyledPath(ren, path, geom.Path{})
}

// Bounds returns the wedge's data-space bounds when applicable.
func (w *Wedge) Bounds(*DrawContext) geom.Rect {
	if w == nil || w.Radius <= 0 || !isDataCoords(w.Coords) {
		return geom.Rect{}
	}
	bounds, _ := pathBounds(w.localPath())
	return bounds
}

func (w *Wedge) localPath() geom.Path {
	outer := specialtyArcPoints(w.Center, w.Radius, w.Theta1, w.Theta2)
	if len(outer) == 0 {
		return geom.Path{}
	}
	if w.Width <= 0 || w.Width >= w.Radius {
		points := make([]geom.Pt, 0, len(outer)+1)
		points = append(points, w.Center)
		points = append(points, outer...)
		return polygonPath(points, true)
	}
	inner := specialtyArcPoints(w.Center, w.Radius-w.Width, w.Theta2, w.Theta1)
	points := make([]geom.Pt, 0, len(outer)+len(inner))
	points = append(points, outer...)
	points = append(points, inner...)
	return polygonPath(points, true)
}

// Draw renders the table cells and text labels.
func (t *Table) Draw(r render.Renderer, ctx *DrawContext) {
	if t == nil || ctx == nil || r == nil || len(t.Cells) == 0 || len(t.Cells[0]) == 0 {
		return
	}
	textRen, ok := r.(render.TextDrawer)
	if !ok {
		return
	}

	for row := range t.Cells {
		for col := range t.Cells[row] {
			cell := t.Cells[row][col]
			if cell.Rect == (geom.Rect{}) {
				continue
			}
			path := buildDisplayPath(ctx, t.Coords, patchRectPath(cell.Rect), geom.Identity())
			r.Path(path, &render.Paint{
				Fill:      cell.Fill,
				Stroke:    t.EdgeColor,
				LineWidth: t.LineWidth,
				LineJoin:  render.JoinMiter,
				LineCap:   render.CapButt,
			})

			text := cell.Text
			if displayTextIsEmpty(text) {
				continue
			}
			anchor := transformedPoint(ctx, t.Coords, geom.Pt{
				X: cell.Rect.Min.X + cell.Rect.W()/2,
				Y: cell.Rect.Min.Y + cell.Rect.H()/2,
			}, 0, 0)
			layout := measureSingleLineTextLayout(r, text, t.FontSize, ctx.RC.FontKey)
			color := t.TextColor
			if cell.IsHeader {
				color = t.HeaderTextColor
			}
			drawDisplayText(textRen, text, alignedSingleLineOrigin(anchor, layout, TextAlignCenter, textLayoutVAlignCenter), t.FontSize, color, ctx.RC.FontKey)
		}
	}
}

// Bounds returns an empty rect so table placement does not affect autoscaling.
func (t *Table) Bounds(*DrawContext) geom.Rect { return geom.Rect{} }

// Z returns the table's draw order.
func (t *Table) Z() float64 { return t.z }

type specialtyViolinSummary struct {
	min    float64
	max    float64
	mean   float64
	median float64
}

func specialtyArcPoints(center geom.Pt, radius, theta1, theta2 float64) []geom.Pt {
	if radius <= 0 {
		return nil
	}
	span := theta2 - theta1
	steps := max(24, int(math.Ceil(math.Abs(span)/3))+1)
	points := make([]geom.Pt, 0, steps)
	for i := range steps {
		t := float64(i) / float64(max(steps-1, 1))
		angle := (theta1 + span*t) * math.Pi / 180
		points = append(points, geom.Pt{
			X: center.X + radius*math.Cos(angle),
			Y: center.Y + radius*math.Sin(angle),
		})
	}
	return points
}

func specialtyHexagon(center geom.Pt, rx, ry float64) []geom.Pt {
	return []geom.Pt{
		{X: center.X + rx, Y: center.Y - ry/2},
		{X: center.X + rx, Y: center.Y + ry/2},
		{X: center.X, Y: center.Y + ry},
		{X: center.X - rx, Y: center.Y + ry/2},
		{X: center.X - rx, Y: center.Y - ry/2},
		{X: center.X, Y: center.Y - ry},
	}
}

func matplotlibHexbinCenter(x, y, xMin, yMin float64, gridX, gridY int, xStep, yStep float64) (hexbinKey, geom.Pt, bool) {
	ix := (x - xMin) / xStep
	iy := (y - yMin) / yStep
	ix1 := int(math.Round(ix))
	iy1 := int(math.Round(iy))
	ix2 := int(math.Floor(ix))
	iy2 := int(math.Floor(iy))

	valid1 := 0 <= ix1 && ix1 <= gridX && 0 <= iy1 && iy1 <= gridY
	valid2 := 0 <= ix2 && ix2 < gridX && 0 <= iy2 && iy2 < gridY
	if !valid1 && !valid2 {
		return hexbinKey{}, geom.Pt{}, false
	}
	d1 := math.Inf(1)
	if valid1 {
		d1 = (ix-float64(ix1))*(ix-float64(ix1)) + 3*(iy-float64(iy1))*(iy-float64(iy1))
	}
	d2 := math.Inf(1)
	if valid2 {
		d2 = (ix-float64(ix2)-0.5)*(ix-float64(ix2)-0.5) + 3*(iy-float64(iy2)-0.5)*(iy-float64(iy2)-0.5)
	}
	if d1 < d2 {
		return hexbinKey{lattice: 0, row: iy1, col: ix1}, geom.Pt{
			X: xMin + float64(ix1)*xStep,
			Y: yMin + float64(iy1)*yStep,
		}, true
	}
	return hexbinKey{lattice: 1, row: iy2, col: ix2}, geom.Pt{
		X: xMin + (float64(ix2)+0.5)*xStep,
		Y: yMin + (float64(iy2)+0.5)*yStep,
	}, true
}

func specialtyFiniteValues(values []float64) []float64 {
	out := make([]float64, 0, len(values))
	for _, value := range values {
		if isFinite(value) {
			out = append(out, value)
		}
	}
	slices.Sort(out)
	return out
}

func specialtyViolinStats(values []float64) specialtyViolinSummary {
	sum := 0.0
	for _, value := range values {
		sum += value
	}
	return specialtyViolinSummary{
		min:    values[0],
		max:    values[len(values)-1],
		mean:   sum / float64(len(values)),
		median: percentileSorted(values, 50),
	}
}

func specialtyKDE(values []float64, points int, bandwidth float64) ([]float64, []float64) {
	if len(values) == 0 {
		return nil, nil
	}
	minValue := values[0]
	maxValue := values[len(values)-1]
	if minValue == maxValue {
		minValue -= 0.5
		maxValue += 0.5
	}
	if bandwidth <= 0 {
		mean := 0.0
		for _, value := range values {
			mean += value
		}
		mean /= float64(len(values))
		variance := 0.0
		for _, value := range values {
			diff := value - mean
			variance += diff * diff
		}
		std := math.Sqrt(variance / float64(len(values)))
		bandwidth = 1.06 * std * math.Pow(float64(len(values)), -0.2)
		if bandwidth <= 0 || !isFinite(bandwidth) {
			bandwidth = (maxValue - minValue) / 12
		}
		if bandwidth <= 0 {
			bandwidth = 1
		}
	}

	grid := make([]float64, points)
	density := make([]float64, points)
	span := maxValue - minValue
	for i := range points {
		t := float64(i) / float64(max(points-1, 1))
		x := minValue + span*t
		grid[i] = x
		sum := 0.0
		for _, value := range values {
			z := (x - value) / bandwidth
			sum += math.Exp(-0.5 * z * z)
		}
		density[i] = sum / (float64(len(values)) * bandwidth * math.Sqrt(2*math.Pi))
	}
	return grid, density
}

func finitePointRect(x, y []float64) geom.Rect {
	var rect geom.Rect
	have := false
	for i := 0; i < min(len(x), len(y)); i++ {
		if !isFinite(x[i]) || !isFinite(y[i]) {
			continue
		}
		pt := geom.Pt{X: x[i], Y: y[i]}
		if !have {
			rect = geom.Rect{Min: pt, Max: pt}
			have = true
			continue
		}
		rect = expandRect(rect, pt)
	}
	if !have {
		return geom.Rect{Min: geom.Pt{}, Max: geom.Pt{X: 1, Y: 1}}
	}
	return rect
}

func piePoint(center geom.Pt, radius, angleDeg float64) geom.Pt {
	rad := angleDeg * math.Pi / 180
	return geom.Pt{
		X: center.X + radius*math.Cos(rad),
		Y: center.Y + radius*math.Sin(rad),
	}
}

func pieAlign(angleDeg float64) TextAlign {
	rad := angleDeg * math.Pi / 180
	switch {
	case math.Cos(rad) < -0.2:
		return TextAlignRight
	case math.Cos(rad) > 0.2:
		return TextAlignLeft
	default:
		return TextAlignCenter
	}
}

func sankeyOrientation(flow float64, orientations []int, i int) int {
	if i < len(orientations) {
		switch {
		case orientations[i] < 0:
			return -1
		case orientations[i] > 0:
			return 1
		}
	}
	if flow < 0 {
		return -1
	}
	return 1
}

func floatAt(values []float64, i int, fallback float64) float64 {
	if i < len(values) && isFinite(values[i]) {
		return values[i]
	}
	return fallback
}

func boolOffset(v bool) int {
	if v {
		return 1
	}
	return 0
}

func specialtyBool(value *bool, fallback bool) bool {
	if value == nil {
		return fallback
	}
	return *value
}

func hideAxesFrame(a *Axes) {
	if a == nil {
		return
	}
	a.ShowFrame = false
	for _, axis := range []*Axis{a.XAxis, a.YAxis, a.XAxisTop, a.YAxisRight} {
		if axis == nil {
			continue
		}
		axis.ShowSpine = false
		axis.ShowTicks = false
		axis.ShowLabels = false
	}
}
